export default function Disclaimer() {
  return (
    <div className="container">
      <h1>Disclaimer</h1>

      <p>
        The information provided on ToolFinance is for general informational and
        educational purposes only.
      </p>

      <h2>No Professional Advice</h2>
      <p>
        All calculators, tools, and content on this website are not intended to
        be a substitute for professional financial, legal, or investment advice.
        Users are encouraged to consult qualified professionals before making
        any financial decisions.
      </p>

      <h2>Accuracy of Information</h2>
      <p>
        While we strive to ensure that all information and calculations are
        accurate and up to date, ToolFinance makes no guarantees regarding the
        completeness, reliability, or accuracy of any content.
      </p>

      <p>
        Results generated by calculators are estimates only and may vary based on
        actual financial conditions.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        ToolFinance shall not be held liable for any losses, damages, or
        consequences arising from the use of this website or reliance on any
        information provided.
      </p>

      <h2>External Links</h2>
      <p>
        This website may contain links to third-party websites. We do not control
        or guarantee the accuracy or reliability of content on external sites.
      </p>
    </div>
  );
}